name: Check for dead links

on: [push, pull_request, workflow_dispatch]

jobs:
  broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6

      - run: |
          cd docs
          bundle install
          jekyll build

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.0
        with:
          args: ./docs/_site/* -b https://opendrr.github.io --exclude *.css