name: Check for dead links on github pages

on:
  push:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  workflow_dispatch:

jobs:
  broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6
          bundler-cache: true

      - run: |
          cd docs
          bundle install
          jekyll build

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.0
        with:
          args: ./docs/_site/* -b https://opendrr.github.io
      
      - name: Add comment if broken links
        if: hashFiles('./lychee/out.md') != '' && ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Broken links found, please check actions log.'
            })

      - name: Check errors
        if: hashFiles('./lychee/out.md') != ''
        run: |
            less ./lychee/out.md
            exit 1