name: Check links

on: 
  push:
  workflow_dispatch:

jobs:
  my-broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Check download links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          #config-file: 'mlc_config.json'
          folder-path: 'docs/'
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://opendrr.github.io/data/
