name: Check links

on: 
  push:
  workflow_dispatch:

jobs:
  my-broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://opendrr.github.io/earthquake-scenarios/
